### ISSUE TITLE
Sphinx 7.2 breaks generated documentation headers

### ISSUE THREAD

**Issue by oddbookworm** [sphinx-doc/sphinx#11618]
### Describe the bug

Updating to sphinx 7.2.0 (or higher, including 7.2.2) breaks our documentation headers at [pygame-ce](https://github.com/pygame-community/pygame-ce). As an example, here's the current [doc page for pygame-ce's draw module](https://github.com/pygame-community/pygame-ce/blob/main/src_c/doc/draw_doc.h), and here's what the doc looks like when I generate locally with 7.2.0 (7.1.2 produces what's on github)
```c
/* Auto generated file: with makeref.py .  Docs go in docs/reST/ref/ . */
#define DOC_DRAW_RECT "rect(surface, color, rect) -> Rect\nrect(surface, color, rect, width=0, border_radius=0, border_top_left_radius=-1, border_top_right_radius=-1, border_bottom_left_radius=-1, border_bottom_right_radius=-1) -> Rect\ndraw a rectangle"
```
The reST source for that doc is [here](https://github.com/pygame-community/pygame-ce/blob/main/docs/reST/ref/draw.rst) and here is our [makeref.py](https://github.com/pygame-community/pygame-ce/blob/main/buildconfig/makeref.py)

### How to Reproduce

Create a pygame-ce dev environment (our github wiki has instructions)
Install sphinx 7.2-7.2.2 (all of these versions give broken doc headers)
`python setup.py docs --fullgeneration`
`python setup.py install`
You should see an error about undefined references to `DOC_****`
Install sphinx 7.1.2 (or earlier) and try again. Should work

### Environment Information

```text
Platform:              linux; (Linux-6.1.44-1-MANJARO-x86_64-with-glibc2.38)
Python version:        3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429])
Python implementation: CPython
Sphinx version:        7.2.2
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.15.1

This is from my local environment, but we also see the issue in our CI runs for MacOS, Windows, Debian/Ubuntu, and ManyLinux
```

**Comment by AA-Turner** [comment]
Hi Andrew (@oddbookworm),

Is there a smaller reproducer at all than setting up an entire pygame environment please? Ideally a stand-alone Sphinx project, but in effect the fewer moving parts the better!

Thanks,
Adam

**Comment by oddbookworm** [comment]
Uh, I don't know enough about how it works to do that myself. Lemme ask around to see if someone else knows enough about our workflow to sort that out

**Comment by dr0id** [comment]
this is on windows:
![image](https://github.com/sphinx-doc/sphinx/assets/231898/63c7ec95-bd21-4807-914f-f08ecdd2f226)
it looks like somewhere this is joined without using os.path.join or similar

**Comment by ankith26** [comment]
I did a bit of digging, and noticed that some change in the `doctree` attribute of the `html-page-context` event breaks our usage. I'm not sure how much this info helps, but I'll dig further and try to isolate the issue into a minimum reproducer later

**Comment by ankith26** [comment]
Though I'm not familiar with the sphinx codebase, to me it looks like a regression from # #11533

**Comment by picnixz** [comment]
@oddbookworm If you are not able to find a minimal reproducer, can you bisect the culprit commit so that we may have an idea of what has been introduced / removed that may have lead to this issue? Thank you.

**Comment by oddbookworm** [comment]
> @oddbookworm If you are not able to find a minimal reproducer, can you bisect the culprit commit so that we may have an idea of what has been introduced / removed that may have lead to this issue? Thank you.

I was able to do that.
https://github.com/sphinx-doc/sphinx/commit/05a14ff007038c45336d18b137718c6eab16f9cf -> works fine
https://github.com/sphinx-doc/sphinx/commit/97d2c5da2fc0262541777d4284c74be8aeebeba3 -> broken

**Comment by AA-Turner** [comment]
This is the last blocker for 7.2.3.

A

**Comment by AA-Turner** [comment]
The issue is caused by these two lines--swapping the order fixes things. I'm continuting to investigate for a proper fix.

https://github.com/sphinx-doc/sphinx/blob/2f6ea1422b08f9494f34b80c2ff6c96b5f396fdc/sphinx/domains/python.py#L1311-L1313

**Comment by AA-Turner** [comment]
See #11647, which should fix this issue.

**Comment by AA-Turner** [comment]
@oddbookworm / @dr0id / @ankith26: please may you test with the Sphinx's master branch?: ``python -m pip install "Sphinx @ git+https://github.com/sphinx-doc/sphinx"``

A

**Comment by ankith26** [comment]
Doesn't fix the issue for me. 

I didn't come up with a minimal reproducer yet, but in the process of testing things out I did find the source of the issue, though I don't understand it well enough.

So basically we have a custom subclass of `docutils.nodes.SparseNodeVisitor` that we use in `doctree.walkabout` (triggered from `doctree-read` event), and this subclass implements a custom `depart_section` which does something like `if node["ids"][0].startswith("module-"): ...` but in the versions that broke our usage, no ids seem to start with `module-`

**Comment by AA-Turner** [comment]
@ankith26 please may you try re-creating your environment from scratch? ``python buildconfig/makeref.py full_generation`` produces identical header files when I run the command locally.

**Comment by ankith26** [comment]
Oh I'm sorry. I don't know what went wrong when I wrote my previous comment, but I just tried again and yes the issue is indeed fixed.

Thanks!

**Comment by AA-Turner** [comment]
Wonderful! Thank you for reporting, this uncovered a very subtle bug that I otherwise would've missed.

A

**Comment by dr0id** [comment]
Thanks for the bugfix, I can confirm if works again.

**Comment by AA-Turner** [comment]
[Sphinx 7.2.4](https://pypi.org/project/Sphinx/7.2.4/) has been released.

A
