### ISSUE TITLE
Conflicting docs regarding code-block spaces

### ISSUE THREAD

**Issue by dylanh724** [sphinx-doc/sphinx#12742]
### Describe the bug

* This [sphinx-doc](https://sphinx-doc-zh.readthedocs.io/en/latest/markup/code.html#line-numbers) shows code block content with 3 spaces
* This [other sphinx-doc](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#directives) shows an example with 7 spaces (scroll down to `.. code-block::`)
* [Anaconda's rst cheatsheet](https://docs.anaconda.com/restructuredtext/#code-blocks) (not official, but "big name official cheatsheet") examples 4 spaces

I then receive warnings "expecting max 1 arg" when I use 3 spaces with `:linenos:` that goes away when I give it 4 spaces (misaligned!).

Overall, it's wildly confusing:

1. Can anyone clarify the *official* way to do this, with and without `:linenos:` (if it makes a difference -- I don't know why it would change the alignment)?
2. Is it possible to update these docs to both use the same spacing examples, and perhaps have an example using `:linenos:` as well? 

This code-block is very mysterious.

### How to Reproduce

Compare my links above

### Environment Information

```text
Platform:              win32; (Windows-10-10.0.22631-SP0)
Python version:        3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        7.4.7
Docutils version:      0.20.1
Jinja2 version:        3.1.4
Pygments version:      2.18.0
```

### Sphinx extensions

```python
n/a
```

**Comment by chrisjsewell** [comment]
Heya, In the one of the links you provide, it gives the answer 😅 https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#directives

> Be careful as the indent is not a fixed number of whitespace, e.g. three, but any number whitespace. This can be surprising when a fixed indent is used throughout the document and can make a difference for directives which are sensitive to whitespace. Compare: ...

**Comment by chrisjsewell** [comment]
It's whatever the indentation of the second line of the directive is

**Comment by dylanh724** [comment]
![image](https://github.com/user-attachments/assets/12c92489-6cf4-491c-a979-a0cea4289176)

I don't know if my coffee isn't kicking in or what, but can you provide an alternate example? In the explanation in the doc, it gives 2 identical code block spaces. I thought the 2nd code block would have been aligned to the directive with -4 spaces, but it's the same, so why does it have no spaces at the beginning?

![image](https://github.com/user-attachments/assets/1ee2eb69-a3e3-480f-946e-a3f1a6ba6fa8)

**Comment by chrisjsewell** [comment]
its determined by the indent of the "first non-blank line"

```restructuredtext
.. directive::
   non-blank

.. directive::

        non-blank
```

**Comment by dylanh724** [comment]
Ahh gotcha I think that's what threw me off: I would never have expected an arg like :caption: be the "starting" non blank line; I very much assumed the code content.

I'd propose to change [this sphinx-doc](https://sphinx-doc-zh.readthedocs.io/en/latest/markup/code.html#line-numbers) to have the code example be more educational rather than "this is a ruby code block". Something in regards to line spacing, and how the *args*, too, must align with the spacing

**Comment by electric-coder** [comment]
> so why does it have no spaces at the beginning?

The [general rules of indentation always hold][1]; that's to say the parser will count the number of spaces (indentation level) of the first non-blank line and expect any subsequent lines within a given block to be consistent with that level.

[1]: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#indentation

**Comment by timhoffm** [comment]
I suggest that we adopt consistent indentation throughout the Sphinx docs. The question is how much?

- 3 spaces is what docutils uses most of the time, but they are also not consistent. They sometimes have 4 spaces, and in rare cases 2 spaces.
- 4 spaces is the python standard. At least in docstrings, it's difficult to have the docstring indented by multiples of 4 and then indent the rst in the docstring by 3 further.

Therefore, my tendency would go towards 4 spaces.

**Comment by timhoffm** [comment]
The 7 spaces are an outlier and should be fixed.

We should aim at consistent spacing. It's similar to Python: While you can use any indentation  as long as you obey the indentation rules, it good to have a consistent best practice.

Docutils as the original source mostly uses 3 spaces, but they are not consistent themselves and also have cases of 4 spaces and on some occasions 2 spaces.

The Sphinx docs mostly uses 3 spaces. I assume this comes from docutils.

I can see an argument for 4 spaces (and partly use this in my projects). In particular in docstrings it is hard to have the docstring indented by multiples of 4 and then add multiples of 3 rst indenting on top. But changing all the indentation in the Sphinx docs is a discussion of its own.

**Comment by electric-coder** [comment]
> Docutils as the original source mostly uses 3 spaces (...) 4 spaces (...) 2 spaces.

I think the main concern is that it's potentially confusing to beginners.

> The Sphinx docs mostly uses 3 spaces. I assume this comes from docutils.

Afaict the original Sphinx discussions boards that might contain the rational for using 3 space indentation are gone since the project migrated to GitHub. The original rational for docutil's using 3 space indentation was likely in some Python sig-group discussion board that's most likely also been deleted. 

> In particular in docstrings it is hard to have the docstring indented by multiples of 4 and then add multiples of 3 rst indenting on top.

My solution is hitting the <kbd>Tab</kbd> regardless as I've never found a reason to using 3 space besides following the documentation examples.

**Comment by AA-Turner** [comment]
> The original rational for docutil's using 3 space indentation was likely in some Python sig-group discussion board that's most likely also been deleted.

The full archives of DOC-Sig going back to 1998(?) still exist. 

If I had to guess at the reason for three space indentation, it is simply that explicit markup in reST uses `\.\. +\w\s*::`, and hence the minimum amount of leading indentation is three (`.. `). I doubt it was an intentional choice, more one that led on from how directives are specified. Note eg lists have a variable indentation, so this is not consistent.

A

**Comment by jfbu** [comment]
Reading this discussion  I discovered a mis-behavior of the "electric-mode" of Emacs in a buffer triggering the ReST major mode.  After having typed:

```rest
.. note::

   hello

.. note::
   :name: test

          tabbing brought me here
```
The TAB key wll align with "test".  Thus output will have extra spaces, as per the current discussion. And I tested with ``rst2html`` which produces:

![Capture d’écran 2024-08-08 à 13 43 49](https://github.com/user-attachments/assets/86018335-e3fd-47c4-a2d9-aaa9895064cb)


Maybe my Emacs ReST mode support is outdated.  Hmm it seems to come with the binary build of Emacs I installed on MacOS via homebrew, I am still using Emacs 28.1.  The source at my computer says
```
;; The latest release of this file lies in the docutils source code repository:
;;   http://docutils.svn.sourceforge.net/svnroot/docutils/trunk/docutils/tools/editors/emacs/rst.el
```
but I can't find any version string in it apart from
```
;; Copyright (C) 2003-2022 Free Software Foundation, Inc.
```

Perhaps I will open a ticket at Docutils home regarding their Emacs `rst.el`.  But first I need to check with their latest version...

**Comment by AA-Turner** [comment]
Docutils doesn't maintain `rst.el` any more, it moved to emacs itself. https://github.com/emacs-mirror/emacs/blob/master/lisp/textmodes/rst.el is the latest I believe.

A

**Comment by jfbu** [comment]
Thanks @AA-Turner I was 2 seconds away from posting  my already written ticket at the Docutils site...

**Comment by electric-coder** [comment]
Docutils really is *that* library from [xkcd 2347][1]...

![dependency_2x](https://github.com/user-attachments/assets/ed28966a-b182-4453-8b3f-829ec7620d90)

[1]: https://xkcd.com/2347/

**Comment by timhoffm** [comment]
> Docutils really is _that_ library

That is true. OTOH it feels like their dev workflows are still from 2003 as well - sourceforge does not have a reasonable developer experience. This makes contributing hard (I've been through this) and thus they don't get much support from new contributors.

**Comment by gmilde** [comment]
> If I had to guess at the reason for three space indentation, it is simply that explicit markup in reST uses `\.\. +\w\s*::`, and hence the minimum amount of leading indentation is three (`.. `). 

Actually, the minimal indentation is ONE. 
Example:
~~~
.. topic:: topic title

 Topic text.

*
 bullet list
 
.. code:: python
 :name: world
 
 print("hello world")
~~~
This may help when browsing rST sources on a smartphone :)

**Comment by gmilde** [comment]
This [other sphinx-doc](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#directives) clarifies "the *official* way to do this, with and without :linenos:" in detail.

It may be amended with another [indentation](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#indentation) peculiarity: without option block, the least indented line of the content block determines what is stripped:
~~~
.. code-block::

       The output of this line starts with four spaces.

   The output of this line has no spaces at the beginning.

This line is not part of the code block.
~~~

@timhoffm 
>  The 7 spaces are an outlier and should be fixed.

The 7 spaces are an essential part of the example detailling the behaviour.
The text before and after it explains this clearly.
