### ISSUE TITLE
Sane Default Image Width in LaTeX Writer

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1275]
I accidentally broke my fork (more used to git) and because I still have a pull request pending, I don't want to delete and refork now. So I put this diff just here. Sorry for the inconvenience.

The problem is this: When you put a random figure into your `.rst` file and parse it with Sphinx you can end up with an image that is bigger than the page it is put on in the pdf. Now you can go ahead and manually resize it with parameters to the `figure` in your `.rst` file, but that is ugly. As a developer you don't want to be concerned with that. You want your picture somewhere in there and you don't want to worry if it should be 70&#37; of it's data size or 546 pixels. You just want it to fit in.

Solution: At least for latex there is a very simple solution: Images can have a width set to something called `textwidth` which does exactly what it says: it figures out how wide the text is and puts that value into width. This is perfect in most situations. So a great thing would be to default to this variable in latex generation. Users just don't have to struggle and everybody is happy.

So here is the diff that does exactly that:

```
#!diff

diff -r f4eaad7d20cd sphinx/writers/latex.py
--- a/sphinx/writers/latex.py   Thu Sep 26 19:25:58 2013 +0200
+++ b/sphinx/writers/latex.py   Fri Sep 27 12:19:42 2013 +0200
@@ -948,6 +948,8 @@
             w = self.latex_image_length(attrs['width'])
             if w:
                 include_graphics_options.append('width=&#37;s' &#37; w)
+        else:
+            include_graphics_options.append('width=\\textwidth')
         if 'height' in attrs:
             h = self.latex_image_length(attrs['height'])
             if h:

```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1275
- Originally reported by: Erik B
- Originally created at: 2013-09-27T12:31:21.887

**Comment by tk0miya** [comment]
At present, Sphinx latex builder uses `\sphinxincludegraphics` macro. It is automatically resizes width.
So this is already resolved. Closing.

**Comment by ltalirz** [comment]
@tk0miya  I'm using sphinx 1.8.5 and the issue still persists, at least with pixel graphics. E.g.

```
.. figure:: include/images/verdi_graph/si/graph-full.png
   :alt:
```
renders at full-width in HTML output but as "actual size" in latex output:

HTML [link](https://aiida-tutorials.readthedocs.io/en/tutorial_2019_05/pages/2019_MARVEL_Psik_MaX/sections/calculations.html#simulate-submission):
![Screenshot 2019-05-10 at 01 10 33](https://user-images.githubusercontent.com/1053245/57492270-83152880-72c0-11e9-93bb-481f9f249059.png)

LATEX:
![Screenshot 2019-05-10 at 01 11 08](https://user-images.githubusercontent.com/1053245/57492272-84deec00-72c0-11e9-8911-762570b4e255.png)

**Comment by tk0miya** [comment]
@ltalirz Confirmed with 1.8.6. But it seems resolved with 2.0.1. I guess #5992 would be fixed your problem. Could you check it please?

Note: my Dockerfile to reproduce:
```
FROM tk0miya/sphinx-pdf

RUN git clone https://github.com/aiidateam/aiida-tutorials
WORKDIR /docs/aiida-tutorials/docs
RUN pip3 install -r requirements.txt
RUN pip3 install -U sphinx
RUN apt install -y pandoc
RUN make latexpdf SPHINXOPTS="-D latex_engine=xelatex"
```

**Comment by ltalirz** [comment]
Thanks, yes, it is fixed in v2!

For this tutorial documentation it's not a big issue to move to python3 - was just trying to stay with sphinx 1.x to give people a choice.

**Comment by tk0miya** [comment]
Good to know. Sphinx 1.x has not been maintained now (because of short of hands...). So I recommend you to upgrade to latest one.
