### ISSUE TITLE
make.bat latexpdf

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1520]
[make.bat](https://github.com/sphinx-doc/sphinx/blob/da20c3713b482926bc59b6c69fa359ed401aa2a1/sphinx/quickstart.py#L792) latexpdf has two problems:

```
#!bat
make all-pdf
cd &#37;&#37;BUILDDIR&#37;&#37;/..
```
1. `make all-pdf` doesn't work. How about `pdflatex &#37;(project_fn)s.tex` instead?
2. `cd &#37;&#37;BUILDDIR&#37;&#37;/..` doesn't work if builddir is a relative path (which is the default). Just use `cd ../..`?

(Probably the same applies to the latexpdfja build rule.)

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1520
- Originally reported by: Anonymous
- Originally created at: 2014-07-25T10:14:02.666

**Comment by shimizukawa** [comment]
_From Peter Suter on 2014-09-25 10:53:58+00:00_

https://bitbucket.org/birkenfeld/sphinx/pull-request/295 takes a different approach for 2.

For 1. the `make all-pdf` does a bit more than just `pdflatex %(project_fn)s.tex`. Maybe `call make.bat all-pdf` and create a `texinputs/make.bat` equivalent to the `texinputs/Makefile`?

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-09-25 17:23:28+00:00_

Merged in psuter/sphinx/psuter/fix-makebat-latexpdf-mechanism-to-cd-bac-1411635021827 (https://bitbucket.org/birkenfeld/sphinx/pull-request/295)

Fix `make.bat latexpdf` mechanism to `cd` back to the build directory. (see #1520)

→ <<cset 7c9565f5104d4ce568c69fe0ad09ef72b399c8f4>>

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-09-25 17:23:28+00:00_

Fix `make.bat latexpdf` mechanism to `cd` back to the build directory. (see #1520)
Set `%BUILDDIR%` to an absolute path using the common `%~dp0` trick.

→ <<cset 7eccc230b7371b1d5fe9853de41bd6dea0cd235e>>

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-09-25 17:23:32+00:00_

Merged in psuter/sphinx/psuter/fix-makebat-latexpdf-mechanism-to-cd-bac-1411635021827 (https://bitbucket.org/birkenfeld/sphinx/pull-request/295)

Fix `make.bat latexpdf` mechanism to `cd` back to the build directory. (see #1520)

→ <<cset 7c9565f5104d4ce568c69fe0ad09ef72b399c8f4>>

**Comment by shimizukawa** [comment]
I close this issue.
Suggestion 2 was reproduced in my environment and it was fixed.
Suggestion 1 is not clear and couldn't reproduce in my env.

**Comment by petsuter** [comment]
Problem 1 is still an issue for me.
I can provide more details. Can you reopen this issue? Or should I create a new issue?

Basically `make.bat latexpdf` only works if you have a `make` installed. But I don't have a `make` installed. (Why would I use `make.bat` if I did?)

```
>make.bat latexpdf
Running Sphinx v1.3.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing test.tex... index
resolving references...
writing... done
copying TeX support files...
done
build succeeded.
'make' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by shimizukawa** [comment]
@petsuter thanks, please create another ticket to avoid confusion. (Now I understand what happen, yes we need `texinputs/make.bat` to support no-make-existent windows environment)

**Comment by petsuter** [comment]
Thanks, I created #1867
