### ISSUE TITLE
Building documentation for a Python 3.4 project leads to intersphinx/autodoc warnings on builtins and others

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1582]
When trying to build a documentation for a Python 3.4 project with activated intersphinx, the following warnings (and others) occur when `sphinx-build -n -b html ...` is executed:

```
#!text

<autodoc>:1: WARNING: py:class reference target not found: unittest.case.TestCase
<autodoc>:1: WARNING: py:class reference target not found: builtins.object
```

The Makefile does not use the '-n' argument (which lets sphinx report all reference errors as warnings). This makes using the '-W' argument (which treats warnings as errors) impossible in automatic test builds.

Intersphinx is enabled, and the Python 3.4 docs are configured:

```
#!python

intersphinx_mapping = {'python': ('https://docs.python.org/3.4', None)}
```

A sample documentation that has these warnings can be found [here at GitHub](https://github.com/edelbluth/arobito-docs/tree/77943daa0bd94967020b1951b410527a3481a07e), and a Travis CI build that shows the warnings [is here](https://travis-ci.org/arobito/arobito-docs/builds/36498044). The configuration file `conf.py` is [here](https://github.com/edelbluth/arobito-docs/blob/77943daa0bd94967020b1951b410527a3481a07e/source/conf.py).

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1582
- Originally reported by: Juergen Edelbluth
- Originally created at: 2014-09-28T20:40:54.930

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-10-02 12:07:11+00:00_

This will have to be fixed on the python.org side.

**Comment by bsipocz** [comment]
I see this issue in our docs of photutils/astropy, too. 

For some reason, the `object` base class is resolved as `'builtins.object'` when `build_sphinx` is run with python3, and it's missing from the default objects.inv (thus seem to be a python.org issue). However when `build_sphinx` is run with python2, it is resolved as `'object'`. Is this the expected, normal behaviour? 

@birkenfeld - Do you know whether this issue was reported to the python guys during the autumn? I haven't found it on their issue tracker.

**Comment by birkenfeld** [comment]
Hmm, probably not. Mostly because I would also be the "python guy" to do it :) I'll have to debug it when I find a bit of time for it.

**Comment by tk0miya** [comment]
Did anyone report to python project? Is there anything to do from Sphinx side?
It seems both are still not registered to 3.6 docs.

**Comment by bsipocz** [comment]
@tk0miya - I can't recall the details but most probably I added that workaround PR for astropy and didn't report it upstream myself.

**Comment by tk0miya** [comment]
Thank you for comment. I think there are nothing to do from sphinx side.
So I'm closing this now.
Thanks,
