### ISSUE TITLE
Characters of ANSI escape sequences are displayed while sphinx-quickstart

### ISSUE THREAD

**Issue by mikanbako** [sphinx-doc/sphinx#1820]
On prompt, ANSI escape sequences are not converted color and their characters are displayed on terminal.

For example, the following is first prompt of sphnx-quickstart. "> Root path for the documentation [.]:" should be purple. But "[35m" and "[39;49;00m" of ANSI escape sequences are displayed by this issue.

```
Welcome to the Sphinx 1.3.1 quickstart utility.

Please enter values for the following settings (just press Enter to
accept a default value, if one is given in brackets).

Enter the root path for documentation.
[35m> Root path for the documentation [.]: [39;49;00m
```

I can reproduce this issue by Sphinx 1.3.1 on the following environment.
- Python 2.7.9 from MacPorts on OS X 10.9.5
- Python 3.4.3 from MacPorts on OS X 10.9.5
- Python 3.4.3 with colorama 0.3.3 on Windows 8.1 (Python 2.7.9 cannot reproduce)

**Comment by mikanbako** [comment]
This issue is a problem of python on MacPorts about OS X.

Installing of py*-readline ports resolves this issue. For example, install py34-readline port for Python 3.4.x on MacPorts.

See https://trac.macports.org/ticket/47827 for detail.

**Comment by Cilyan** [comment]
Same problem here with all sphinx tools on Windows 7 with Python 2.7.6 Sphinx installed using `pip install sphinx`. This makes spotting errors rather difficult when compiling documentation...

**Comment by shimizukawa** [comment]
Sorry for the inconvenience.
I think https://github.com/tartley/colorama/issues/49 is a related issue,

There are workarounds, please choose one and do it:
1. `pip uninstall colorama`
2. `set TERM=`
3. `set SPHINXOPTS=-N` (not perfect)

**Comment by Cilyan** [comment]
Thanks, I use the workaround `set TERM=` successfully and placed it in the `make.bat`. I do not know why `TERM` is set here, but it's maybe due to MSys Git. By default, it is set to `nutc`.

**Comment by minchinweb** [comment]
Came across the same issue today -- Windows 10, Python 3.4.3, Sphinx 1.3.1.

Oddly, the bolded text seems to work, but the coloured text doesn't.

![sphinx-quickstart 8312015 93228 am](https://cloud.githubusercontent.com/assets/1548809/9582633/db741ca8-4fc3-11e5-8866-f9683ea725dd.png)

**Comment by mikanbako** [comment]
This cause of issue on Windows may be a bug of Python 3.4.

colorama wraps sys.stdout for colored prompt but Python 3.4 does not wrap sys.stdout in input().
See [Issue24402](http://bugs.python.org/issue24402) for detail.

**Comment by shimizukawa** [comment]
This problem has been fixed at https://github.com/tartley/colorama/issues/48. please wait next version of colorama (maybe 0.3.4).

**Comment by mikanbako** [comment]
I installed colorama on master branch and ran sphinx-quickstart on cmd (on Windows 8.1 and Python 3.4.3) but this problem is not fixed. Because my cmd does not set TERM when I reported this issue.

But when I installed [pyreadline](https://pypi.python.org/pypi/pyreadline) and colorama 0.3.3 (on PyPI), this problem is fixed.

**Comment by artob** [comment]
Encountered this just now with Sphinx 1.3.3 running on Python 2.7 installed from MacPorts. Installing `pyreadline`, with either `pip` or `port`, did not improve matters. The workaround of `unset TERM` does improve matters a little.

**Comment by shimizukawa** [comment]
https://pypi.python.org/pypi/colorama/0.3.5 has been fixed this issue.

**Comment by shimizukawa** [comment]
(memo) How to reproduce this issue
1. invoke 'command prompt' by cmd.exe
2. if you use Win10, set "Use legacy console" check box in option
3. Install Sphinx-1.3.x (1.3, 1.3.1, 1.3.2, 1.3.3)
4. Install colorama-0.3.3
5. set TERM=xterm
6. do `make html`

![20160106-71019](https://cloud.githubusercontent.com/assets/151623/12129494/60631b3e-b447-11e5-8d1e-bc84b5f9ef12.jpg)

**Comment by rdbisme** [comment]
Hello, this still happens for me within a virtualenv (while outside of it it doesn't occur).

OS: macOS Sierra 10.12.2
System-wide Python: 2.7.13 and 3.5.2
Virtualenv: Python 2.7.13

I also installed `py27-readline` and `py35-readline` from macports.

**Comment by shimizukawa** [comment]
@rubendibattista please try this checker https://gist.github.com/shimizukawa/6560350301847813c1e37487c6b79a03 and let me know the result of it
