### ISSUE TITLE
sphinx.ext.napoleon: Parameters with only type are rendered incorrectly

### ISSUE THREAD

**Issue by cmeeren** [sphinx-doc/sphinx#2135]
Consider the following docstring:

``` python
def toYearFraction(date):
    '''Converts :class:`datetime.date` or :class:`datetime.datetime` to decimal year.

    Parameters
    ==========
    date : :class:`datetime.date` or :class:`datetime.datetime`

    Returns
    =======
    year : float
        Decimal year

    Notes
    =====
    The algorithm is taken from http://stackoverflow.com/a/6451892/2978652

    '''
```

It produces the following output (using [sphinx_rtd_theme](https://github.com/snide/sphinx_rtd_theme), but I do not think that's where the issue lies):

![parm](https://cloud.githubusercontent.com/assets/7766733/11420338/bb9abe60-942d-11e5-9b5c-a0c6a123bd39.png)

As you can see, there is a dash after the parameter type for `date`, even though no description was provided (in this case I would say it is self-explanatory). The dash should be removed if no explanation is given.

**Comment by RobRuana** [comment]
I can't reproduce this issue with the docstring quoted above.

I believe this has been fixed in the repo with #1927, but a new version with the fixed code hasn't been released yet.

You can try using the sphinxcontrib-napoleon package ('sphinxcontrib.napoleon' instead of 'sphinx.ext.napoleon' in conf.py). You'll need to pip install sphinxcontrib-napoleon or add sphinxcontrib-napoleon to your requirements.txt.

sphinxcontrib-napoleon usually has more up-to-date fixes.

Thanks for the report, and let me know if that doesn't fix this issue!

**Comment by cmeeren** [comment]
Hi, I tried using sphinxcontrib-napoleon instead (added to requirements.txt) but the issue remains.

**Comment by RobRuana** [comment]
Did you also enable it in the Sphinx conf.py?

**Comment by cmeeren** [comment]
Yes, I replaced `sphinx.ext.napoleon` with `sphinxcontrib.napoleon`.

**Comment by RobRuana** [comment]
Can you post the exact version of sphinx and napoleon you are using?

**Comment by cmeeren** [comment]
sphinx 1.3.1
sphinxcontrib-napoleon 0.4.3 (when using sphinxcontrib.napoleon instead of sphinx.ext.napoleon)

Building on readthedocs

**Comment by cmeeren** [comment]
Here's the build log for the sphinxcontrib-napoleon build: https://readthedocs.org/projects/apexpy/builds/3524853/

Here's the build log for the latest build using sphinx.ext.napoleon: https://readthedocs.org/projects/apexpy/builds/3525109/

**Comment by RobRuana** [comment]
This is very odd... Here is a screenshot of that exact docstring rendered with Sphinx 1.3.1 and Napoleon 0.4.3 on my system. Is it possible readthedocs.org is serving a cached or stale build of the documentation?

![napoleon](https://cloud.githubusercontent.com/assets/2592431/11482024/65050922-9755-11e5-9847-6ed52c8a348c.png)

**Comment by RobRuana** [comment]
For what it's worth, I've experienced issues with stale builds on readthedocs.org. Is there any way you can verify the rendered html is the from the latest build? Perhaps a version number or another change you can check to verify the html is being overwritten?

**Comment by cmeeren** [comment]
I always check the revision number at the bottom, which is the first characters in the Git commit hash. It has always checked out. That should be sufficient, right?

**Comment by RobRuana** [comment]
That should be sufficient to verify the latest docs are building.

Perhaps the build environment is stale? You could try following the directions [here](http://read-the-docs.readthedocs.org/en/latest/builds.html#deleting-a-stale-or-broken-build-environment) to wipe the build environment.

I've had to do that before on my own projects to get the docs to build correctly.

**Comment by cmeeren** [comment]
Tried to wipe all versions and re-build (using sphinx.ext.napoleon) but no luck, [the problem is still there](http://apexpy.readthedocs.org/en/latest/reference/helpers.html#apexpy.helpers.toYearFraction).

I don't know if I'm supposed to get any confirmation that the version is wiped when clicking "Wipe", I got none (I was sent to an "are you sure" page and clicked Wipe again and was sent back to the version list).

**Comment by RobRuana** [comment]
The correct solution to this issue is to set `napoleon_use_param = False` in your conf.py. `sphinxcontrib.napoleon` is not needed, `sphinx.ext.napoleon` works fine.

Thank you for your patience while I figured this out!

When `napoleon_use_param = True` (the default value) Napoleon will correctly render the following:

```
    Parameters
    ==========
    date : :class:`datetime.date` or :class:`datetime.datetime`
```

as reStructuredText:

```
    :param date:
    :type date: :class:`datetime.date` or :class:`datetime.datetime`
```

The sphinx html builder then renders that with a dash at the end. When `napoleon_use_param = False` Napoleon recognizes that there is no description for the parameter, and renders it without the dash as:

```
   :Parameters: **date** (:class:`datetime.date` or :class:`datetime.datetime`)
```

**Comment by cmeeren** [comment]
Great, it worked! Thank you so much. Are there any downsides to use `napoleon_use_param=False`?

**Comment by RobRuana** [comment]
The only downside is if you are using another third party extension that is explicitly looking for the `:param NAME:` style formatting. However, I am not actually aware of any conflicts with any other extensions.

There may also be some slight styling differences depending on the theme you are using, but again, I am not aware of any actual conflicts.
- `napoleon_use_param = False` turns your parameters into a plain ordered list with the label **Parameters**
- `napoleon_use_param = True` turns your parameters into structured data that other extensions can further manipulate

This is okay in most cases, because by default sphinx just turns the structured parameter data into a plain ordered list anyway :)

**Comment by cmeeren** [comment]
I can confirm that using [this conf.py](https://github.com/cmeeren/apexpy/blob/8ee3a1d5f85600dcba174496cfc15eee8dfc83e1/docs/conf.py) there is no visible difference on ReadTheDocs.

**Comment by RobRuana** [comment]
Cool, thank you for all your input on this!
