### ISSUE TITLE
Math is not HTML-encoded when :nowrap: is given (jsmath, mathjax)

### ISSUE THREAD

**Issue by bgeron** [sphinx-doc/sphinx#2226]
```
Test document
=============

.. math::
    :nowrap:

    a<b>c
```

Expected result: valid HTML
Actual result: `a<b>c` occurs verbatim in HTML, math is not rendered, `c` is shown in bold.
Tested with: Sphinx 1.3.3; MathJax

The problem seems to be that [here](https://github.com/sphinx-doc/sphinx/blob/7c6a3b2/sphinx/ext/jsmath.py#L29) and [here](https://github.com/sphinx-doc/sphinx/blob/7c6a3b2/sphinx/ext/mathjax.py#L33), in the `:nowrap:` case, the call to `self.encode(..)` is forgotten.

**Comment by tk0miya** [comment]
Fixed at c8c6dc1
Thank you for reporting

**Comment by bgeron** [comment]
Thanks!

**Comment by lilisha100** [comment]
The problem still exists in the released 1.5.3.

In the mathax.py file in 1.5.3, from line 32 to line 33:
    if node['nowrap']:
        self.body.append(self.encode(node['latex']))

Codes to add math delimiters are missing. It should be:

    if node['nowrap']:
        self.body.append(self.builder.config.mathjax_display[0] +
                         self.encode(node['latex']) +
                         self.builder.config.mathjax_display[1])

**Comment by jfbu** [comment]
Remark:

the markup

```
.. math::
   :nowrap:

   a<b>c
```

is incorrect. It should be

```
.. math::
   :nowrap:

   \[a<b>c\]
```

Indeed, `:nowrap:` is explained [here](http://www.sphinx-doc.org/en/stable/ext/math.html#directive-math) and it says that the math environment is to be provided by user.

Notice that for example `a_b^c` will cause failed PDF build via LaTeX, if not wrapped in `\[a_b^c\]`.

Besides, html MathJaX display is also wrong without the `\[..\]` wrapping.

**Comment by bgeron** [comment]
Fair remark. I simply gave the smallest possible example, but maybe it was unrealistically small.
