### ISSUE TITLE
Nested field lists inside list items cause unwanted space in HTML output

### ISSUE THREAD

**Issue by rweickelt** [sphinx-doc/sphinx#2258]
The HTML output of the following code 

```
- item 1
- item 2

  :field1: value
  :field2: value
```

contains additional vertical vertical space between each list item. This does not occur when omitting the field list.

Tested on xubuntu, amd64, sphinx release 1.3.4.

**Comment by tk0miya** [comment]
In my short investigation:

The behavior comes from docutils (base library of Sphinx).
In `docutils.writers.html4css1.HTMLTranslator`, docutils generates `<p>` tag if list includes any items excepting paragraphs and nested lists.

To fix this, set `self.compact_simple` in visit_list_item instead of `visit_bullet_list` and `visit_enumerated_list`.
But we have to know why docutils check whole of list.

**Comment by Paebbels** [comment]
Are you referring to the following behavior?

![docutils_bug3](https://cloud.githubusercontent.com/assets/956109/15506134/acf8bb06-21c6-11e6-8588-65643a99a729.PNG)

Sphinx (+ docutils) seams to inserts a paragraph for a list item (`<li>`-tag), if it contains other elements then simple text. But this behavior is not consequent / deterministic. See this example:

![docutils_bug4](https://cloud.githubusercontent.com/assets/956109/15506195/000fd6b2-21c7-11e6-980a-6ee7c95d7b7d.PNG)

There is no spacing and no paragraph in the HTML source code.

It's questionable, why sphinx distinguishes between simple and complex list items. And why simple list items are not enclosed in paragraphs.

**Comment by rweickelt** [comment]
Yes. That's the issue.

**Comment by Paebbels** [comment]
Any progress on this issue?

**Comment by tk0miya** [comment]
Nothing chnaged. PR is always welcome :-)

**Comment by CPCer** [comment]
> In my short investigation:
> 
> The behavior comes from docutils (base library of Sphinx).
> In `docutils.writers.html4css1.HTMLTranslator`, docutils generates `<p>` tag if list includes any items excepting paragraphs and nested lists.
> 
> To fix this, set `self.compact_simple` in visit_list_item instead of `visit_bullet_list` and `visit_enumerated_list`.
> But we have to know why docutils check whole of list.

hello, could you tell me did you mean to modify file `_html_base.py`? and then what to do...
As a newbie i thought there're any setting like `self.compact_simple = visit_bullet_list` or `self.compact_simple = visit_enumerated_list` but i just can't find it, so i think I was too naive...

Did you mean cutting those "self.compact_simple" codes and paste to where `visit_list_item` is defined...

THX so much...

**Comment by tk0miya** [comment]
Sorry, I forget what I meant. All I can say is please read docutils' code. To customize the behavior, you need to know how docutils works. `_html_base.py` is a base class of HTML writers.

On the other hand, this is already resolved in Sphinx-2.0 because we'd moved to HTML5 writer.

**Comment by jeff5** [comment]
> On the other hand, this is already resolved in Sphinx-2.0 because we'd moved to HTML5 writer.

In Sphinx v2.2.0, I still get this:
```
One fish, two fish,

    •   red fish, blue fish,

        ◦ black fish,
        ◦ blue fish,
    •   old fish,

new fish.
```
A work-around at the first level is to put a comment before the outer list continues, to force an above-list space.
```
One fish, two fish,

* red fish, blue fish,

  * black fish,
  * blue fish,

.. Padding. See https://github.com/sphinx-doc/sphinx/issues/2258

* old fish,

new fish.

```

**Comment by tk0miya** [comment]
I don't know what theme do you use. If my understanding correct, you can control the margins with theme's CSS or custom CSS when you use HTML5 writer.

**Comment by jhachtel** [comment]
> > On the other hand, this is already resolved in Sphinx-2.0 because we'd moved to HTML5 writer.
> 
> In Sphinx v2.2.0, I still get this:
> 
> ```
> One fish, two fish,
> 
>     •   red fish, blue fish,
> 
>         ◦ black fish,
>         ◦ blue fish,
>     •   old fish,
> 
> new fish.
> ```
> 
> A work-around at the first level is to put a comment before the outer list continues, to force an above-list space.
> 
> ```
> One fish, two fish,
> 
> * red fish, blue fish,
> 
>   * black fish,
>   * blue fish,
> 
> .. Padding. See https://github.com/sphinx-doc/sphinx/issues/2258
> 
> * old fish,
> 
> new fish.
> ```


Still an issue, apparently.

This answer worked perfectly for me. Here's my reST:

![Capture](https://user-images.githubusercontent.com/22918571/78396804-fcdf9000-75bd-11ea-8ad9-9cf3d5c78b33.PNG)
