### ISSUE TITLE
toctree generates empty ul with class "simple"

### ISSUE THREAD

**Issue by SupaHam** [sphinx-doc/sphinx#2705]
Hey, I have discovered a bug with toctree and :titlesonly:.

Whenever you use toctree like so:

```
.. toctree::
   :maxdepth: 2
   :titlesonly:

   some/entry/file
```

A ToC tree is generated, all good.
# Problem

However sometimes it can generate an `li` with a `ul` with class="simple" immediately following it. This can get really obnoxious since `ul`s tend to have margins, thus creating unexpected spaces.
# What's causing it

Due to the way Sphinx currently handles the `:titlesonly:` code, when an `li` previously had a subheading entry then the :titlesonly: code runs, it removes the li elements but it doesn't actually remove the ul if it is empty afterwards.

See https://github.com/sphinx-doc/sphinx/blob/a35399a0aa5b8804aab238d5f2ccacd7608c213a/sphinx/environment.py#L1432

Thanks to @bendem for locating the code.

**Comment by tk0miya** [comment]
Fixed at    1e97909.
Thank you for reporting!

**Comment by Zarthus** [comment]
Comment removed; I was wrong! Originally I set the requirements.txt to the wrong branch, which made it appear still broken. I've verified it works now though :)

Thanks!

**Comment by bendem** [comment]
@Zarthus was using the wrong branch, it is fixed.
