### ISSUE TITLE
Text with footnote with a huge image makes footnotes to appear incorrectly

### ISSUE THREAD

**Issue by gdalmau** [sphinx-doc/sphinx#4037]
### Problem
When a page in `.rst` file is going to finish with an image / graph that doesn't fit, it makes a new page starting with this image, but footnotes on the previous page show incorrectly in the half of the page and it should appear at the bottom.

#### Procedure to reproduce the problem
1- Have a `index.rst` with the following:

```rst
Seciton with Footnote
=====================

This has a footnote [1]_ but the footnote doesn't appear at the bottom of the
page.


.. graphviz::
   :align: center

.. digraph:: some_random_digraph

      graph [fontsize=12];
      node [shape="box"];
      rankdir=LR;

      Pts [label="..."]
      
      P [label="Planificació"]
      F1 [label="Fase 1"]
      F2 [label="Fase 2"]
      F3 [label="Fase 3"]
      IT1 [label="Iteració 1"]
      IT2 [label="Iteració 2"]
      IT3 [label="Iteració 3"]
      T1 [label="Tasca 1"]
      T2 [label="Tasca 2"]
      T3 [label="Tasca 3"]
      T4 [label="Tasca 4"]
      T5 [label="Tasca 5"]

      P -> F1;
      P -> F2;
      P -> F3;

      F1 -> IT1;
      F1 -> IT2;

      F2 -> IT3;
      F3 -> Pts;

      IT1 -> T1;
      IT1 -> T2;
      IT2 -> T3;
      IT3 -> T4;
      IT3 -> T5;


.. rubric:: Footnotes
.. [1] Footnote text
```
2- Generate pdf
```
make latexpdf
```

3- The resulting pdf has a footnote that should be at the bottom of the page

#### Error logs / results
There are no error logs

#### Expected results
The footnotes should always be at the bottom of the page.

### Environment info
- OS: Ubuntu 16.04.3
- Python version: 2.7.12
- Sphinx version: 1.6.3
- Latexmk version: 4.41

**Comment by jfbu** [comment]
This is a pure LaTeX problem which can be reproduced without Sphinx from this latex document:

```latex
\documentclass[letterpaper,10pt]{report}
\usepackage{geometry}
\usepackage{graphicx}
\usepackage{mwe}
\begin{document}

\chapter{A chapter}

\section{A section}
This has a footnote
\footnote{Footnote text} but the footnote doesn’t appear at the bottom of the
page.

This is random text. This is random text. This is random text. This is random
text. This is random text. This is random text. This is random text. This is
random text. This is random text. This is random text. This is random text.
This is random text. This is random text. This is random text. This is random
text. This is random text. This is random text. This is random text. This is
random text. This is random text. This is random text. This is random text.
This is random text. This is random text. This is random text. This is random
text. This is random text. This is random text. This is random text. This is
random text. This is random text. This is random text. This is random text.
This is random text. This is random text. This is random text. This is random
text. This is random text. This is random text. This is random text. This is
random text. This is random text. This is random text. This is random text.
This is random text. This is random text. This is random text. This is random
text. This is random text. This is random text. This is random text. This is
random text. This is random text. This is random text. This is random text.

\includegraphics{example-image.pdf}

\end{document}
```

If however the graphics inclusion is done inside a LaTeX ``figure`` environment (which floats in the LaTeX way), like this:

```latex
\begin{figure}[htbp]
\centering
\includegraphics{example-image.pdf}
\end{figure}
```

then the problem goes away.

Thus, I think only way to fix this would be for `graphviz` extension to arrange for use of a figure environment in latex output. (I have not looked more closely so far).

*edit*: which is automatically the case if ``:caption:`` option is used, see [comment](https://github.com/sphinx-doc/sphinx/issues/4037#issuecomment-326746585) below.

**Comment by jfbu** [comment]
With your example, I could use ``raw:: latex`` directive to fix it:

```rst
.. raw:: latex

   \begin{figure}[htbp]
   \centering

.. digraph::  some_random_digraph

   graph [fontsize=12];
   node [shape="box"];
   rankdir=LR;

   Pts [label="..."]
   
   P [label="Planificació"]
   F1 [label="Fase 1"]
   F2 [label="Fase 2"]
   F3 [label="Fase 3"]
   IT1 [label="Iteració 1"]
   IT2 [label="Iteració 2"]
   IT3 [label="Iteració 3"]
   T1 [label="Tasca 1"]
   T2 [label="Tasca 2"]
   T3 [label="Tasca 3"]
   T4 [label="Tasca 4"]
   T5 [label="Tasca 5"]

   P -> F1;
   P -> F2;
   P -> F3;

   F1 -> IT1;
   F1 -> IT2;

   F2 -> IT3;
   F3 -> Pts;

   IT1 -> T1;
   IT1 -> T2;
   IT2 -> T3;
   IT3 -> T4;
   IT3 -> T5;

.. raw:: latex

   \end{figure}
```

But in your use case, perhaps this makes the graph appear in some unexpected place.

**Comment by jfbu** [comment]
If you give a caption to your graph, like this

```rst
.. digraph::  some_random_digraph
   :caption: A caption

   graph [fontsize=12];
   ...
```

it will use LaTeX `figure` environment for LaTeX output and the problem is solved.

**Comment by gdalmau** [comment]
**Update**: not solved.

[This](https://github.com/sphinx-doc/sphinx/issues/4037#issuecomment-326746276) seemed to solve the problem. It makes the graph to appear in the next page and the footnotes appear correctly, but the text you write below the graph appear in wrong position in above it.

Also adding a `:caption:` option works but I don't want it because it's not aligned with the text.

**Comment by gdalmau** [comment]
@jfbu The problem is with big images (.jpg, .png ...) and big graphs. If i use `.. figure::` directive instead of image the same problem happens. The image appears in the next page but the text I wrote above it appears on top of it, filling the empty space of the previous page.

Feel free to ask if I'm not explaining it correctly.

**Comment by jfbu** [comment]
You mean the text which is after the image in the source ends up filling the empty space in the previous page? this is indeed what using `figure` LaTeX environment leads too.

I am afraid there is no solution here: either use a LaTeX "float" environment (such as figure, table, or a custom one declared for example using `float` LaTeX package) and then the image will float to where space is available, and the space it liberates will be occupied by other elements, or use direct box inclusion like `\includegraphics` does and then if the too big object is moved to next page, the previous one has big empty gap. Plus the footnote problem you observed which is a LaTeX/TeX thing basically out of control of Sphinx.

**Comment by gdalmau** [comment]
> You mean the text which is after the image in the source ends up filling the empty space in the previous page? this is indeed what using figure LaTeX environment leads too.

Exactly.

> [...]  Plus the footnote problem you observed which is a LaTeX/TeX thing basically out of control of Sphinx.

Okay thanks, I thought there would be at least a LaTeX solution for this problem.

**Comment by jfbu** [comment]
Sorry about that.

You can fix your problem this way:

```rst
Welcome to FOO's documentation!
===============================


Section
-------

This has a footnote [1]_ but the footnote doesn't appear at the bottom of the
page.

This is random text. This is random text. This is random text. This is random
text. This is random text. This is random text. This is random text. This is
random text. This is random text. This is random text. This is random text.
This is random text. This is random text. This is random text. This is random
text. This is random text. This is random text. This is random text. This is
random text. This is random text. This is random text. This is random text.
This is random text. This is random text. This is random text. This is random
text. This is random text. This is random text. This is random text. This is
random text. This is random text. This is random text. This is random text.
This is random text. This is random text. This is random text. This is random
text. This is random text. This is random text. This is random text. This is
random text. This is random text. This is random text. This is random text.
This is random text. This is random text. This is random text. This is random
text. This is random text. This is random text. This is random text. This is
random text. This is random text. This is random text. This is random text.

.. raw:: latex

   \vfill
   \hrule height 0pt\relax

.. digraph::  some_random_digraph

   graph [fontsize=12];
   node [shape="box"];
   rankdir=LR;

   Pts [label="..."]
   
   P [label="Planificació"]
   F1 [label="Fase 1"]
   F2 [label="Fase 2"]
   F3 [label="Fase 3"]
   IT1 [label="Iteració 1"]
   IT2 [label="Iteració 2"]
   IT3 [label="Iteració 3"]
   T1 [label="Tasca 1"]
   T2 [label="Tasca 2"]
   T3 [label="Tasca 3"]
   T4 [label="Tasca 4"]
   T5 [label="Tasca 5"]

   P -> F1;
   P -> F2;
   P -> F3;

   F1 -> IT1;
   F1 -> IT2;

   F2 -> IT3;
   F3 -> Pts;

   IT1 -> T1;
   IT1 -> T2;
   IT2 -> T3;
   IT3 -> T4;
   IT3 -> T5;


.. rubric:: Footnotes
.. [1] Footnote text
```

but it is not an automated solution because the raw latex must be injected _only_ if next image turns out to be too big. So if your document evolves maybe you will have to suppress it.

You could try posting the code from my [comment](https://github.com/sphinx-doc/sphinx/issues/4037#issuecomment-326745808) on https://tex.stackexchange.com/ as it is pure LaTeX. You could point out someone suggested adding

```latex
\vfill
\hrule height 0pt\relax
```

before the `\includegraphics` but you are looking for an automated solution, as your document is evolving. Oh, but the way

```
.. raw:: latex

   \clearpage
```

is even simpler. So your post on tex.sx could be "is there some automated way rather than manually adding the `\clearpage`" ?

**Comment by gdalmau** [comment]
I don't know how Sphinx does the translation from an `.rst` into LaTeX format, but the following seems to be the workaround for big images that I already know they will appear in another page.

```rst
.. raw:: latex

   \clearpage
```

Thanks for the help

**Comment by jfbu** [comment]
@gdalmau Can we close this issue?

**Comment by gdalmau** [comment]
Sure. Thanks
