### ISSUE TITLE
ValueError: path is on mount 'C:', start on mount 'D:'

### ISSUE THREAD

**Issue by mgpcs** [sphinx-doc/sphinx#4783]
Subject: ValueError: path is on mount 'C:', start on mount 'D:'

### Problem
I'am getting a Warning, if the Sourcefiles are located at a different Drive than the Drive of the Destinationpath. No Warning at Version 1.6.7.

#### Procedure to reproduce the problem
Call "sphinx-build -b html <D:\...> <C:\...>".

#### Error logs / results
```
sphinx-err-847fe2th.log

# Sphinx version: 1.7.2
# Python version: 3.6.5rc1 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   done
#   
#   dumping object inventory...
#   
#   done
#   
#   build succeeded.
#   
#   
#   
# Loaded extensions:
#   alabaster (0.7.10) from c:\users\user\appdata\local\programs\python\python36\lib\site-packages\alabaster\__init__.py
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\sphinx\cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\sphinx\application.py", line 345, in build
    'outdir': path.relpath(self.outdir),
  File "c:\users\user\appdata\local\programs\python\python36\lib\ntpath.py", line 586, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'C:', start on mount 'D:'
```
### Environment info
- OS: Windows (Version 10.0.16299 Build 16299)
- Python version: 3.6.5rc1
- Sphinx version: 1.7.2

**Comment by tk0miya** [comment]
Fixed by #4807 
Thank you for reporting!

**Comment by qq470647251** [comment]
Sphinx v1.8.1
win10
python3.5

the problem is still occurred:
ValueError: path is on mount 'C:', start on mount 'd:'

**Comment by BorderCloud** [comment]
Same problem I think but in the version 2.2.1 of Sphinx.
I need to create a new issue ?

Logs:
```
# Sphinx version: 2.2.1
# Python version: 3.7.5 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.3
# Last messages:
#   reading sources... [ 46%] format_sp
#   reading sources... [ 48%] format_spc
#   reading sources... [ 51%] formats
#   reading sources... [ 53%] generated/specio.core.CannotReadSpectraError
#   reading sources... [ 55%] generated/specio.core.Dict
#   reading sources... [ 58%] generated/specio.core.Format
#   reading sources... [ 60%] generated/specio.core.FormatManager
#   reading sources... [ 62%] generated/specio.core.Request
#   reading sources... [ 65%] generated/specio.core.Spectrum
#   reading sources... [ 67%] generated/specio.core.format.Reader
# Loaded extensions:
#   sphinx.ext.mathjax (2.2.1) from c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.1) from c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.2) from c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.12) from c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\alabaster\__init__.py
#   sphinx.ext.autodoc (2.2.1) from c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\ext\autodoc\__init__.py
#   sphinx.ext.doctest (2.2.1) from c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\ext\doctest.py
#   sphinx.ext.viewcode (2.2.1) from c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\ext\viewcode.py
#   sphinx.ext.githubpages (2.2.1) from c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\ext\githubpages.py
#   sphinx.ext.autosummary (2.2.1) from c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\ext\autosummary\__init__.py
#   sphinx.ext.intersphinx (2.2.1) from c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\ext\intersphinx.py
#   sphinx_gallery.gen_gallery (0.4.0) from c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx_gallery\gen_gallery.py
#   numpydoc (0.9.1) from c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\numpydoc\__init__.py
#   sphinx_issues (unknown version) from D:\PROJET\VRAC2\specio\doc\sphinxext\sphinx_issues.py
#   sphinx.ext.linkcode (2.2.1) from c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\ext\linkcode.py
#   specio_ext (unknown version) from D:\PROJET\VRAC2\specio\doc\sphinxext\specio_ext.py
Traceback (most recent call last):
  File "c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\application.py", line 346, in build
    self.builder.build_update()
  File "c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\builders\__init__.py", line 299, in build_update
    len(to_build))
  File "c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\builders\__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\builders\__init__.py", line 418, in read
    self._read_serial(docnames)
  File "c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\builders\__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\builders\__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\io.py", line 326, in read_doc
    pub.publish()
  File "c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\docutils\core.py", line 218, in publish
    self.apply_transforms()
  File "c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\docutils\core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\transforms\__init__.py", line 90, in apply_transforms
    super().apply_transforms()
  File "c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\docutils\transforms\__init__.py", line 172, in apply_transforms
    transform.apply(**kwargs)
  File "c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\transforms\__init__.py", line 386, in apply
    self.app.emit('doctree-read', self.document)
  File "c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\application.py", line 450, in emit
    return self.events.emit(event, *args)
  File "c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "c:\users\daria\appdata\local\programs\python\python37\lib\site-packages\sphinx\ext\linkcode.py", line 60, in doctree_read
    uri = resolve_target(domain, info)
  File "D:\PROJET\VRAC2\specio\doc\sphinxext\github_link.py", line 62, in _linkcode_resolve
    start=os.path.dirname(__import__(package).__file__))
  File "c:\users\daria\appdata\local\programs\python\python37\lib\ntpath.py", line 562, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'D:', start on mount 'c:'
```

**Comment by tk0miya** [comment]
@BorderCloud your case was caused by github_link extension. So please let this know to their project. Thanks,
```
  File "D:\PROJET\VRAC2\specio\doc\sphinxext\github_link.py", line 62, in _linkcode_resolve
    start=os.path.dirname(__import__(package).__file__))
  File "c:\users\daria\appdata\local\programs\python\python37\lib\ntpath.py", line 562, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'D:', start on mount 'c:'
```

**Comment by BorderCloud** [comment]
@tk0miya Ok thanks
