### ISSUE TITLE
Too strict class/function/... matching in Sphinx >= 1.7.0

### ISSUE THREAD

**Issue by robsan00** [sphinx-doc/sphinx#4946]
Subject: Too strict class/function/... matching in Sphinx >= 1.7.0

### Problem
- I think that matching of class / function / ... is too strict in Sphinx 1.7.0. This was introduced with the fix for #3927.

#### Procedure to reproduce the problem
Consider the following example:
```
def ham(ham_par):
    """Ham.

    :param None ham_par: Ham parameter.
    """
    pass

def spam(spam_par):
    """Spam.

    :param int or None spam_par: Spam parameter.
    """
    pass
```
The method "ham" will build fine, spam will not. From what I understand both functions are documented using perfectly fine syntax (at least PyCharm can deal with it).

#### Error logs / results
```
 WARNING: py:class reference target not found: None
```

#### Expected results
If a strict match (in this case py:class None) is not found there should be some fallback to use other types (in this case py:data None, from what I can see in the intersphinx inventory).

### Environment info
- OS: Windows 10
- Python version: 2.7.x
- Sphinx version: 1.7.4

**Comment by tk0miya** [comment]
Fixed by #4993.
Thanks you for reporting.

**Comment by robsan00** [comment]
I tried this out with version 1.7.5 and the problem still occurs. Anyway I have encountered similar problems with other built-ins as well (e.g. datetime.datetime or file)

**Comment by tk0miya** [comment]
Reopened. Could you tell me your error in detail please?
On my local, it seems reference to `None` works fine.

In addition, `datetime.datetime` works fine too. Did you mean `datetime` instead?
I can reproduce the case of `file`. Certainly it is warned. But it is also warned in 1.6.7.

**Comment by robsan00** [comment]
Sorry, my bad, the example where `None` is still not working is a bit different:

    def spam_none1():
        """Spam1.
    
        :return: Spam2.
        :rtype: None
        """
        return None

Regarding `file`: the following used to work without warning 1.6.7 but does not with 1.7.5:

    def spam_file(ham):
        """Spam.
    
        :param file ham: Ham.
        """
        pass

Regarding `datetime.datetime`: you are right, it is actually `datetime`. It is correct behaviour that the reference here is not found and an error in my code (there is no sense in describing a variable as the `datetime` module).

I am currently going over a list of types that make problem since the update from 1.6.7 to 1.7.x. Shell I add them to this issue or should I open a new one?

**Comment by tk0miya** [comment]
Good point. I missed `:rtype:` field. Surely, it is not supported.

On the other hand, `file` is defined as `py:function` in py2 doc.
Do you want to link to `file()` function? I feel it is a bit strange...
https://github.com/python/cpython/blame/2.7/Doc/library/functions.rst#L470

Personally, I feel "File Objects" section is better. But there are no way to refer it from type fields.
https://docs.python.org/2/library/stdtypes.html#bltin-file-objects

>I am currently going over a list of types that make problem since the update from 1.6.7 to 1.7.x. Shell I add them to this issue or should I open a new one?

Please add them here. Let's continue discussing :-)

**Comment by tk0miya** [comment]
I fixed `:rtype:` case by #5172.

Are there still problematic types?

**Comment by tk0miya** [comment]
It seems this issue is not updated for a long time. And reported issues were already fixed. So I'm closing this now.
Please file a new issue if you still have issues.
Thank you for reporting.
