### ISSUE TITLE
Add left/right option for agogo sidebar

### ISSUE THREAD

**Issue by vanosg** [sphinx-doc/sphinx#6729]
Would it be possible to create a theme option that allows the user to customize which side of the page the Table of Contents/Search bar displays on, for the agogo theme? Most of our users visually expect a TOC to be on the right side of the screen, and is more in line with things like readthedocs.io formatting as well. 

Perhaps add a sidebarjustify option to theme.conf, that accepts the values of right or left, and place the sidebar accordingly?

**Comment by tk0miya** [comment]
Good point. +1.

I prefer `leftsidebar: true` for the purpose because we've already use `rightsidebar` option to determine the place of sidebar on some themes (ex. classic and bizstyle).

If you're interested in, could you make a pull request please?

**Comment by vanosg** [comment]
I would love to help, but I'm not an css guy unfortunately. If you told me what code needed to be added/moved and where, I'm sure I could muddle through, but by that time it may just be easier for you to do. Sorry... but I'm glad you are interested in the idea. Happy to support or test however else I can though. Thank you!

**Comment by tk0miya** [comment]
Okay, I just posted #6732 for this proposal. Please try it. I'll release it in next release.

**Comment by vanosg** [comment]
Setting it to false looks just like I would hope it would, placed nicely on the left. However, I tried it with 'true' as well just to try and help test, and it placed the TOC above all content. 
False (looks good!):

![s_left](https://user-images.githubusercontent.com/2440369/66710614-e872b700-ed41-11e9-92e4-c465eac87f1c.jpg)

True (Content starts below the TOC):
![s_right](https://user-images.githubusercontent.com/2440369/66710615-f0325b80-ed41-11e9-9983-63a91f5ed2da.jpg)

My theme.conf file is stock, except for changing the rightsidebar value. I'm viewing in Firefox 69.0.2 on Ubuntu. Is there any other information I can provide to help? I'm happy to continue to test things. Maybe it's "just me" though

THANK YOU though, for taking the time to add in this change!

**Comment by tk0miya** [comment]
OMG... I'll take a look

**Comment by tk0miya** [comment]
Fixed again. extra margin was inserted on last PR. Now I use a "padding" to insert space instead.

@vanosg Could you try this again please? If not working well, please let me know your `html_theme_options`. And please check your document contains a wide object spreading contents area (ex. image, table and so on).

**Comment by vanosg** [comment]
Still the same issue

```html_theme_options = {'headerfont':'"Open Sans", sans serif', 'headerlinkcolor':'87bdd8', 'headerbg':'#86AAD3', 'linkcolor':'#336699'}```

You can view the current set of docs at http://docs.eggheads.org . No images really, but we do have several rather large tables in the docs. But, even 'simple' pages like http://docs.eggheads.org/mainDocs/partyline.html render with the TOC above when applying this with rightsidebar = true . 

If you want to play with our docs yourself, you can download them from https://github.com/eggheads/eggdrop and see if its 'just me'. In the repo, head to docs/sphinx_source/ and run make -B html , you should be able to view them yourself if that makes testing easier- at least you can figure out if its 'just me' or not! Let me know what else I can do

**Comment by vanosg** [comment]
And I'll clarify, the docs at that link use the current master branch, they're not using this PR branch

**Comment by tk0miya** [comment]
Thank you for the repo. I found the reason of drop the content column. The html_logo higher than header conflicts with sidebar in my PR. I fixed my PR again. Please check it please!

**Comment by vanosg** [comment]
Looks good, both true and false! This is why I don't mess with css, I could never do this. Thanks again for bearing this burden, and the fast turn around time. Sphinx is great!

**Comment by tk0miya** [comment]
Thank you for quick confirmation! just merged. It will be released in next release (maybe soon).
