### ISSUE TITLE
Non-public instance attributes are not documented without __slots__

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#956]
There is an inconsistency with the way hidden instance attributes (ie. attributes whose name starts with an underscore, and which are set in the **init** method) are documented, compared to public instance attributes.

If I do the following...
# Create a new-style class
# Don't specify a **slots** attribute
# In the **init** method, create a public attribute and document it with #:
# In the **init** method, create a hidden attribute and document it with #:
# Use autoclass to document it (with the private-members parameter)

...then the public attribute will appear in the documentation (with a value of None), but the hidden attribute will not.

I have attached some minimal Python and RST to demonstrate the problem.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/956
- Originally reported by: Gary Donovan
- Originally created at: 2012-06-27T04:46:19.973

**Comment by buxx** [comment]
Affected to. This bug have been fixed ? It will be ?

**Comment by TheMagSec** [comment]
issue still there! 

in `sphinx.util.inspect` change the function `safe_getattr`:

```
def safe_getattr(obj, name, *defargs):
    """A getattr() that turns all exceptions into AttributeErrors."""
    try:
        if name.startswith("__") and not name.endswith("__"):
            obj_name = obj.__name__    
            if "_%s%s"%(obj_name,name) in obj.__dict__:
                name = "_%s%s"%(obj_name,name)
        return getattr(obj, name, *defargs)
    except Exception as error:
        # this is a catch-all for all the weird things that some modules do
        # with attribute access
        if defargs:
            return defargs[0]
        raise AttributeError(name)    
```

this will remove the error.
To remove the protected namespace-constants from your generated docs, change the function `filter_members` inside `sphinx.ext.autodoc`:

```
def filter_members(self, members, want_all):
    # [...] 
    for (membername, member) in members:
        # [...]
        elif want_all and membername.startswith('_'):
            # ignore members whose name starts with _ by default
            keep = self.options.private_members and \
                            not membername.startswith('_'+namespace) and\  # <- ADD THIS LINE
                            (has_doc or self.options.undoc_members)    
        # [...]
```

**Comment by katyhuff** [comment]
I'm affected by this. @MagSec-Arts ... are you planning to PR your suggested fix?

**Comment by fbauzac** [comment]
I'm hitting a problem (using sphinx-build 1.4.6), maybe the same:

```
/home/fbauzac/git/bms/docs/code/bmslib.utils.rst:34: WARNING: autodoc: failed to import attribute u'OptionOrigins._origins' from module u'bmslib.utils.confparse'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fbauzac/virtualenv/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 526, in import_object
    obj = self.get_attr(obj, part)
  File "/home/fbauzac/virtualenv/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 422, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/home/fbauzac/virtualenv/local/lib/python2.7/site-packages/sphinx/util/inspect.py", line 125, in safe_getattr
    raise AttributeError(name)
AttributeError: _origins
```

**Comment by Terris-Dianomic** [comment]
Found this today. I found this github issue via https://stackoverflow.com/questions/30312637/instance-attribute-error  .

5 year old issue? Am I doing something wrong?

**Comment by tk0miya** [comment]
Is this still in trouble? It seems working with 2.0.
Please let me know if you're still in problem.

```
# index.rst
.. autoclass:: example.Test
   :members:
   :undoc-members:
   :private-members:
```
```
# example.py
class Test:
    def __init__(self):
        #: A foo bar instance attribute !
        self._foo = 'bar'
```

**Comment by tk0miya** [comment]
I'm closing this now.
Please feel free to reopen if you're still in problem.
Thanks,
